version: '3.1'
services:
  stat-server:
    build: stat-service/stat-server
    image: stat-server-image
    container_name: stat-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db-container:5432/stat
      - SPRING_DATASOURCE_USERNAME=admin_stat
      - SPRING_DATASOURCE_PASSWORD=1yWX1bnLDH3leGPOLeJAvLjLPx8ktKH

  stat-db:
    image: postgres:latest
    container_name: stat-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=admin_stat
      - POSTGRES_PASSWORD=1yWX1bnLDH3leGPOLeJAvLjLPx8ktKH

  editor-service:
    build: editor-service
    image: editor-service-image
    container_name: editor-service-container
    ports:
      - "8080:8080"
    depends_on:
      - updater-db
      - stat-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://updater-db-container:5432/updater
      - SPRING_DATASOURCE_USERNAME=admin_updater
      - SPRING_DATASOURCE_PASSWORD=CrpDcdW9E2N1KHbJBRrsM9PzWv80xKZ

  updater-db:
    image: postgres:latest
    container_name: updater-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=updater
      - POSTGRES_USER=admin_updater
      - POSTGRES_PASSWORD=CrpDcdW9E2N1KHbJBRrsM9PzWv80xKZ